### ISSUE TITLE
UnicodeDecodeError 

### ISSUE THREAD

**Issue by karl-an** [ugorsahin/TalkingHeads#77]
Hi there, 

i try to reproduce the example from the start page and i get the following error: 

>>> from talkingheads import PiClient
>>> chathead = PiClient()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\bikraak\talkingheads\.venv\Lib\site-packages\talkingheads\model_library\pi.py", line 18, in __init__
    super().__init__(
  File "C:\Users\bikraak\talkingheads\.venv\Lib\site-packages\talkingheads\base_browser.py", line 149, in __init__
    version_main=detect_chrome_version(driver_version),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bikraak\talkingheads\.venv\Lib\site-packages\talkingheads\utils.py", line 56, in detect_chrome_version
    out = re.search(r"Google\s+Chrome\s+(\d{3})", out.decode())
                                                  ^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 41: invalid start byte

**Comment by ugorsahin** [comment]
It appears that the program is unable to decode the output of the `google-chrome --version` command. You can manually specify your current Google Chrome version by using the `driver_version` argument when instantiating, for example `PiClient(driver_version=128)`. 

Please also provide the output of `<path-to-google-chrome> --version` via the command line (or PowerShell), to help me observe the output of the command.
